version: "2"

services:
  node-1:
    build: .
    environment:
      TITLE: 'FILE NOT FOUND'
      DESCRIPTION: '404'
      NAME: 'https://www.soniccity-records.de'
      URL: 'https://www.soniccity-records.de'
  lb:
    image: rancher/lb-service-haproxy:v0.7.9
    ports:
    - 8087:8087/tcp